version: '3.8'

services:
  excalidraw-postgres:
    image: postgres:latest
    container_name: excalidraw-postgres
    environment:
      POSTGRES_USER: postgres   
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: excalidraw_db    
    ports:
      - "5432:5432"                
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data:
    driver: local
